############
# Database #
############
# Oracle12c: Oracle DB 12c r2 or later
# PostgreSQL95: PostgreSQL 9.5 or later
# SQLServer2012: Microsoft SQL Server 2012 or later
database.platform=PostgreSQL95
database.ip=192.168.85.213
database.port=9010
database.username=aims
database.password=ENC(BTug1m3UiYg0Xd4So57n+w==)

database.core.name=AIMS_CORE_DB
database.portal.name=AIMS_PORTAL_DB
database.pda.name=AIMS_PORTAL_DB
database.ota.name=AIMS_OTA_DB
database.sensor.name=$sensordbname
#database.connectionString.extendedParameters=;multiSubnetFailover=true;loginTimeout=200;

database.core.ip=192.168.85.213
database.core.port=9010
database.core.username=aims
database.core.password=ENC(ZuNv+BFs4UxjGlFNCfwUBQ==)

database.portal.ip=192.168.85.213
database.portal.port=9010
database.portal.username=aims
database.portal.password=ENC(QvbTlKD0dPRWOBgwNi0emA==)

database.pda.ip=192.168.85.213
database.pda.port=9010
database.pda.username=aims
database.pda.password=ENC(yzsPUxpDDjAjPAWRH07Dow==)

database.ota.ip=192.168.85.213
database.ota.port=9010
database.ota.username=aims
database.ota.password=ENC(yPCtdumaTQ+EHBS8TR8g6Q==)

database.sensor.ip=192.168.85.213
database.sensor.port=9010
database.sensor.username=aims
database.sensor.password=ENC(r+xY3WAbAQmvz1QozVHIMA==)

##################################
# AIMS (Change requires restart) #
##################################
# AIMS Core  #
aims.core.url.scheme=http
aims.core.url.host=localhost
aims.core.url.path=core
aims.core.url.port=9001
aims.core.input.path=${aims.root.path}/bin/core/input/
aims.core.accessPoint.firmware.validation=true
#aims.core.accessPoint.firmware.minVersion=
aims.core.accessPoint.firmware.upgrade.url=/${aims.dashboard.service.url.path}/common/otamanager/api/gw/getFirmwareFile
aims.core.accessPoint.launched.backOffPeriod=30m
#aims.core.accessPoint.maxContractCount=500
#aims.core.accessPoint.maxContractSize=254KB
#aims.core.accessPoint.maxLaunch=
aims.core.ntp.server.ip=
aims.core.http.basicAuth.username=aims
aims.core.http.basicAuth.password=ENC(9uWD5eTG0XmmivDQ/noEMg==)

################
# AIMS Portal  #
################
aims.portal.debug=false
aims.portal.url.scheme=http
aims.portal.url.host=localhost
aims.portal.url.port=9001
aims.portal.url.path=
aims.gateway.port=

# AIMS Dashboard Web  #
aims.dashboard.service.url.path=dashboardservice
aims.dashboard.service.url.scheme=http
aims.dashboard.service.url.host=localhost
aims.dashboard.service.url.port=9001

# File path
customer.file.input.path=${aims.root.path}/inf/input
customer.file.backup.path=${aims.root.path}/inf/backup
customer.file.pattern=*.dat
customer.file.duplicates=false
customer.file.numberOfRowsPerOnce=1000

# File Process Log
customer.file.result.log=DB

# Select customer
customer.name=standard
customer.class.name=ItemStandard

# Setting parser
customer.file.use.fixedlength=false
customer.file.parser.delimiter=;
#customer.file.encoding=GBK

# Password Policy Configuration
aims.portal.pw.policy.enable=true
aims.portal.pw.policy.minimum.length=8

####################################    
# Nsystem Device Configuration     #
####################################
# LED config : ledIndex(FF: Don't use Setting) | ledMode( 00:default, 01:use config Param) | ledActiveDutyVal( default : 10 * 100usec) | ledActiveTime(default : 3 * 10msec) | ledInactiveTime(default : 3 * 10msec) | ledIdleTime(default : 1 * 1sec) | ledBlinkingCnt ( default : 5)
nsystem.device.led=01010A03030105
solum.esl.ndevice.config.aliveinterval=24
solum.esl.ndevice.config.aesenable=false
solum.esl.ndevice.config.acsenable=false
solum.esl.ndevice.config.losttime=0
solum.esl.ndevice.config.logodisplaytime=0
solum.esl.ndevice.config.beaconlosslimit=10
solum.esl.ndevice.config.reactivationretrylimit=2
solum.esl.ndevice.config.scanperiodset=0
solum.esl.ndevice.config.batterymode=0
solum.esl.ndevice.config.location=1
solum.esl.ndevice.config.tapgostarttime=9
solum.esl.ndevice.config.tapgoendtime=21
solum.esl.ndevice.config.flexibleDefault=1
solum.esl.ndevice.config.noiseCheckTime=30
solum.esl.ndevice.config.noiseThreshold=85
solum.esl.ndevice.config.updatePageUnlock=false

#########################
## LB                   #
#########################
lb.url.host=
lb.url.port=
lb.url.scheme=

#########################
## Tap & Go             #
#########################
tapAndGo.url=

#########################
## LDAPS                #
#########################
ldaps.key.path=C:\\Program Files\\AIMS\\util\\jre\\lib\\security\\cacerts
ldaps.key.password=changeit

#########################
## PDA                #
#########################
aims.pda.route.portal.url=http://192.168.85.213:${aims.portal.url.port}
aims.pda.route.dashboardservice.url=http://192.168.85.213:${aims.dashboard.service.url.port}
aims.pda.route.apigateway.url=
aims.pda.route.sensor.url=http://192.168.85.213:${aims.sensor.url.port}

#########################
## OTA Manager          #
#########################
ota.manager.url=/${aims.dashboard.service.url.path}/common/otamanager
ota.manager.url.port=9001
ota.manager.maxhour=5
ota.manager.intervalminutes=20

#########################
## RabbitMQ             #
#########################
rabbitmq.enable=false
rabbitmq.addresses=localhost:5671
rabbitmq.ssl.store-password=ENC(7JgtKS8AxlkSj11U6oS9K5xq/Kc665T1)
rabbitmq.user.name=aims
rabbitmq.user.password=ENC(isr7biD5KoIIqwGsDnxJlg==)
rabbitmq.vhost=/
rabbitmq.proxy.address=localhost:5671
#rabbitmq.listener.max-concurrency=8

#########################
## Zipkin               #
#########################
zipkin.enable=false
zipkin.url=localhost:9411

# AIMS Link #
aims.link.enable=false
aims.link.url.scheme=http	
aims.link.url.host=localhost
aims.link.url.path=link
aims.link.url.port=9001
# AIMS FONT Path #
#customer.font.file.path=${aims.root.path}/util/jre/lib/fonts

# AIMS Sensor #
aims.sensor.enable=false
aims.sensor.url.scheme=http
aims.sensor.url.host=192.168.85.213
aims.sensor.url.path=sensor
aims.sensor.url.port=9001
aims.sensor.url.th.inbound=/sensor/th/inbound
aims.sensor.url.core.inbound=/sensor/core/inbound

#########################
## AIMS PACKAGES        #
#########################
aims.packages=ota
