-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


ALTER TABLE IF EXISTS public.accesspoint DROP CONSTRAINT IF EXISTS fk_s4ij9i441u1ibm88n8wj4w5lt;

ALTER TABLE IF EXISTS public.config_content DROP CONSTRAINT IF EXISTS fk_config_content_id_content_id;

ALTER TABLE IF EXISTS public.content DROP CONSTRAINT IF EXISTS fk_47li4qpcetc8web2s96ugwhnc;

ALTER TABLE IF EXISTS public.content DROP CONSTRAINT IF EXISTS fk_6fl30jaj1ouw3wamk4ms04p0b;

ALTER TABLE IF EXISTS public.enddevice DROP CONSTRAINT IF EXISTS fk_3qif2492oh45794xm9nj65qyf;

ALTER TABLE IF EXISTS public.enddevice DROP CONSTRAINT IF EXISTS fk_enddevice_controller_id_enddevice_id;

ALTER TABLE IF EXISTS public.enddevice DROP CONSTRAINT IF EXISTS fk_qh6kb6x2fepon0sviumwr6nrl;

ALTER TABLE IF EXISTS public.generation_content_message DROP CONSTRAINT IF EXISTS fk_h8vf0yrbyhvcjry14bnpjdgqg;

ALTER TABLE IF EXISTS public.image_content DROP CONSTRAINT IF EXISTS fk_p37aqpcq5hwkmnau5ua2kwtsl;

ALTER TABLE IF EXISTS public.multi_segment_content DROP CONSTRAINT IF EXISTS fk_1dcpkyhuue3hxjpjh07iaunt0;

ALTER TABLE IF EXISTS public.nfc_content DROP CONSTRAINT IF EXISTS fk_hsg8o13rdiu4oqy0tnt96atte;

ALTER TABLE IF EXISTS public.schedule_content DROP CONSTRAINT IF EXISTS fk_us1qgsab9n6eodsok1db3j3ad;

ALTER TABLE IF EXISTS public.segment_content DROP CONSTRAINT IF EXISTS fk_ns9qgsab9k6kbatok1db6j6ad;

ALTER TABLE IF EXISTS public.sgateway DROP CONSTRAINT IF EXISTS fk_3ydbq4t19asp4e1x4sls7jna2;

ALTER TABLE IF EXISTS public.sgateway_activation DROP CONSTRAINT IF EXISTS fk_pp004wjord3dg2wcu7v3jknir;

ALTER TABLE IF EXISTS public.slabel DROP CONSTRAINT IF EXISTS fk_1n1gc1e331asajy0a55548d0q;

ALTER TABLE IF EXISTS public.slabel_button DROP CONSTRAINT IF EXISTS fk_5kf58cn0352l83s7oceg71pmw;

ALTER TABLE IF EXISTS public.station_white_list DROP CONSTRAINT IF EXISTS fk_jc1m4u8g87ijm12xr3nqys0yq;



DROP TABLE IF EXISTS public.accesspoint;

CREATE TABLE IF NOT EXISTS public.accesspoint
(
    id bigint NOT NULL,
    code character varying(100) COLLATE pg_catalog."default",
    group_id character varying(100) COLLATE pg_catalog."default",
    ip_address character varying(255) COLLATE pg_catalog."default",
    mac_address character varying(50) COLLATE pg_catalog."default",
    type character varying(50) COLLATE pg_catalog."default",
    state character varying(50) COLLATE pg_catalog."default",
    name character varying(100) COLLATE pg_catalog."default",
    uri_scheme character varying(10) COLLATE pg_catalog."default",
    port integer,
    init boolean,
    firmware_version character varying(50) COLLATE pg_catalog."default",
    station_id bigint,
    last_connection_date timestamp without time zone,
    api_version integer,
    white_list_fetch_type character varying(30) COLLATE pg_catalog."default",
    max_launch integer,
    launched integer,
    launched_time character varying(50) COLLATE pg_catalog."default",
    version bigint,
    CONSTRAINT accesspoint_pkey PRIMARY KEY (id),
    CONSTRAINT uk_8ypkg94a4je1fvluw8w3c47rp UNIQUE (mac_address),
    CONSTRAINT uk_mpf8ux1sj5ey7hjh2fh4dxw1w UNIQUE (code)
);

DROP TABLE IF EXISTS public.config_content;

CREATE TABLE IF NOT EXISTS public.config_content
(
    id bigint NOT NULL,
    compressed_data_size bigint,
    CONSTRAINT config_content_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.content;

CREATE TABLE IF NOT EXISTS public.content
(
    id bigint NOT NULL,
    code character varying(100) COLLATE pg_catalog."default",
    group_id character varying(100) COLLATE pg_catalog."default",
    type character varying(50) COLLATE pg_catalog."default",
    state character varying(50) COLLATE pg_catalog."default",
    compression_type character varying(50) COLLATE pg_catalog."default",
    content text COLLATE pg_catalog."default",
    contract text COLLATE pg_catalog."default",
    message_group_id character varying(100) COLLATE pg_catalog."default",
    message_sequence bigint,
    index integer,
    send_time timestamp without time zone,
    status_update_time timestamp without time zone,
    enddevice_id bigint,
    station_id bigint,
    checksum integer,
    process_update_time timestamp without time zone,
    message_type character varying(50) COLLATE pg_catalog."default",
    jobnumber bigint,
    data_size bigint,
    send_new boolean,
    version bigint,
    CONSTRAINT content_pkey PRIMARY KEY (id),
    CONSTRAINT uk_8ls7vylrfbei3dsx543v0do68 UNIQUE (code)
);

DROP TABLE IF EXISTS public.databasechangelog;

CREATE TABLE IF NOT EXISTS public.databasechangelog
(
    id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    author character varying(255) COLLATE pg_catalog."default" NOT NULL,
    filename character varying(255) COLLATE pg_catalog."default" NOT NULL,
    dateexecuted timestamp without time zone NOT NULL,
    orderexecuted integer NOT NULL,
    exectype character varying(10) COLLATE pg_catalog."default" NOT NULL,
    md5sum character varying(35) COLLATE pg_catalog."default",
    description character varying(255) COLLATE pg_catalog."default",
    comments character varying(255) COLLATE pg_catalog."default",
    tag character varying(255) COLLATE pg_catalog."default",
    liquibase character varying(20) COLLATE pg_catalog."default",
    contexts character varying(255) COLLATE pg_catalog."default",
    labels character varying(255) COLLATE pg_catalog."default",
    deployment_id character varying(10) COLLATE pg_catalog."default"
);

DROP TABLE IF EXISTS public.enddevice;

CREATE TABLE IF NOT EXISTS public.enddevice
(
    id bigint NOT NULL,
    state character varying(50) COLLATE pg_catalog."default",
    code character varying(100) COLLATE pg_catalog."default",
    mac_address character varying(50) COLLATE pg_catalog."default",
    message_group_id character varying(100) COLLATE pg_catalog."default",
    message_sequence bigint,
    group_id character varying(100) COLLATE pg_catalog."default",
    type character varying(50) COLLATE pg_catalog."default",
    mode character varying(16) COLLATE pg_catalog."default",
    reactive boolean,
    nfc_data character varying(240) COLLATE pg_catalog."default",
    accesspoint_id bigint,
    station_id bigint,
    has_schedule boolean,
    status_update_time character varying(50) COLLATE pg_catalog."default",
    message_type character varying(50) COLLATE pg_catalog."default",
    unassign_mode character varying(10) COLLATE pg_catalog."default",
    process_update_time timestamp without time zone,
    version bigint,
    led_config character varying(14) COLLATE pg_catalog."default",
    pages character varying(100) COLLATE pg_catalog."default",
    category character varying(30) COLLATE pg_catalog."default",
    controller_id bigint,
    CONSTRAINT enddevice_pkey PRIMARY KEY (id),
    CONSTRAINT uk_qlst4aqhbmpnjetlgdacujft1 UNIQUE (code),
    CONSTRAINT uk_qvbo42f5b86e8wnv1fbtagrvh UNIQUE (mac_address)
);

DROP TABLE IF EXISTS public.generation_content_message;

CREATE TABLE IF NOT EXISTS public.generation_content_message
(
    id bigint NOT NULL,
    server_id bigint NOT NULL,
    content_id bigint NOT NULL,
    type character varying(50) COLLATE pg_catalog."default",
    enddevice_id bigint NOT NULL,
    accesspoint_id bigint,
    enddevice_type character varying(50) COLLATE pg_catalog."default",
    index integer,
    send_new boolean,
    message_type character varying(50) COLLATE pg_catalog."default",
    jobnumber bigint,
    transmission_sequence bigint,
    checksum integer,
    update_time character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT generation_content_message_pkey PRIMARY KEY (id),
    CONSTRAINT uk_d7jgw862weloyvm59ssrnp0od UNIQUE (server_id, content_id, accesspoint_id, transmission_sequence)
);

DROP TABLE IF EXISTS public.image_content;

CREATE TABLE IF NOT EXISTS public.image_content
(
    id bigint NOT NULL,
    compressed_data_size bigint,
    file_name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT image_content_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.job_message;

CREATE TABLE IF NOT EXISTS public.job_message
(
    id bigint NOT NULL,
    server_id bigint,
    job_name character varying(50) COLLATE pg_catalog."default",
    message text COLLATE pg_catalog."default",
    update_time timestamp without time zone,
    load_sequence bigint,
    CONSTRAINT job_message_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.multi_segment_content;

CREATE TABLE IF NOT EXISTS public.multi_segment_content
(
    id bigint NOT NULL,
    file_name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT multi_segment_content_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.nfc_content;

CREATE TABLE IF NOT EXISTS public.nfc_content
(
    id bigint NOT NULL,
    nfc_data character varying(240) COLLATE pg_catalog."default",
    CONSTRAINT nfc_content_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.schedule_content;

CREATE TABLE IF NOT EXISTS public.schedule_content
(
    id bigint NOT NULL,
    count integer,
    CONSTRAINT schedule_content_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.segment_content;

CREATE TABLE IF NOT EXISTS public.segment_content
(
    id bigint NOT NULL,
    file_name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT segment_content_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.server;

CREATE TABLE IF NOT EXISTS public.server
(
    id bigint NOT NULL,
    code character varying(100) COLLATE pg_catalog."default",
    group_id character varying(100) COLLATE pg_catalog."default",
    core_revision character varying(50) COLLATE pg_catalog."default",
    core_version character varying(50) COLLATE pg_catalog."default",
    description character varying(255) COLLATE pg_catalog."default",
    ip_address character varying(255) COLLATE pg_catalog."default",
    type character varying(50) COLLATE pg_catalog."default",
    lb_ip_address character varying(255) COLLATE pg_catalog."default",
    lb_port integer,
    version bigint,
    port integer,
    last_connection_date timestamp without time zone,
    CONSTRAINT server_pkey PRIMARY KEY (id),
    CONSTRAINT uk_96tx503up4941ibvsnhh8itdi UNIQUE (ip_address),
    CONSTRAINT uk_bkn3q2jc3n4qei2uikik9lrwj UNIQUE (code)
);

DROP TABLE IF EXISTS public.sgateway;

CREATE TABLE IF NOT EXISTS public.sgateway
(
    id bigint NOT NULL,
    config text COLLATE pg_catalog."default",
    status text COLLATE pg_catalog."default",
    CONSTRAINT sgateway_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.sgateway_activation;

CREATE TABLE IF NOT EXISTS public.sgateway_activation
(
    sgateway_id bigint NOT NULL,
    mac_address character varying(50) COLLATE pg_catalog."default" NOT NULL,
    short_address integer,
    attribute character varying(100) COLLATE pg_catalog."default",
    handoff boolean,
    update_time character varying(50) COLLATE pg_catalog."default",
    type_code character varying(3) COLLATE pg_catalog."default",
    handoff_sequence bigint NOT NULL,
    CONSTRAINT sgateway_activation_pkey PRIMARY KEY (sgateway_id, mac_address, handoff_sequence)
);

DROP TABLE IF EXISTS public.shedlock;

CREATE TABLE IF NOT EXISTS public.shedlock
(
    name character varying(64) COLLATE pg_catalog."default" NOT NULL,
    locked_by character varying(255) COLLATE pg_catalog."default" NOT NULL,
    locked_at timestamp without time zone NOT NULL DEFAULT now(),
    lock_until timestamp without time zone NOT NULL,
    CONSTRAINT uk_q5g9fxgk5y37ir6ibx3widg2y UNIQUE (name)
);

DROP TABLE IF EXISTS public.slabel;

CREATE TABLE IF NOT EXISTS public.slabel
(
    id bigint NOT NULL,
    firmware_version integer,
    update_status character varying(50) COLLATE pg_catalog."default",
    attribute character varying(100) COLLATE pg_catalog."default",
    alarm_status character varying(10) COLLATE pg_catalog."default",
    temperature integer,
    led_sequence integer DEFAULT 0,
    battery_level character varying(50) COLLATE pg_catalog."default",
    data_channel_rssi integer,
    wakeup_channel_rssi integer,
    info character varying(70) COLLATE pg_catalog."default",
    short_address integer,
    picking_status text COLLATE pg_catalog."default",
    product_info character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT slabel_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.slabel_button;

CREATE TABLE IF NOT EXISTS public.slabel_button
(
    slabel_id bigint NOT NULL,
    index integer NOT NULL,
    presses character varying(300) COLLATE pg_catalog."default",
    CONSTRAINT slabel_button_pkey PRIMARY KEY (slabel_id, index)
);

DROP TABLE IF EXISTS public.station;

CREATE TABLE IF NOT EXISTS public.station
(
    id bigint NOT NULL,
    code character varying(100) COLLATE pg_catalog."default",
    group_id character varying(100) COLLATE pg_catalog."default",
    description character varying(255) COLLATE pg_catalog."default",
    name character varying(100) COLLATE pg_catalog."default",
    company character varying(100) COLLATE pg_catalog."default",
    zone_id character varying(50) COLLATE pg_catalog."default",
    ip_ntp_server character varying(100) COLLATE pg_catalog."default",
    division_code integer,
    white_list_enabled boolean,
    white_list_update_time timestamp without time zone,
    config text COLLATE pg_catalog."default",
    lbs_enabled boolean,
    country character varying(100) COLLATE pg_catalog."default",
    region character varying(100) COLLATE pg_catalog."default",
    city character varying(100) COLLATE pg_catalog."default",
    acs_request_list text COLLATE pg_catalog."default",
    version bigint,
    accesspoints_update_time character varying(50) COLLATE pg_catalog."default",
    server_sent_event_types text COLLATE pg_catalog."default",
    acs_channel_mask text COLLATE pg_catalog."default",
    CONSTRAINT station_pkey PRIMARY KEY (id),
    CONSTRAINT uk_1mq0bkovmdvo63nfgcmtxrgd4 UNIQUE (code)
);

DROP TABLE IF EXISTS public.station_white_list;

CREATE TABLE IF NOT EXISTS public.station_white_list
(
    station_id bigint NOT NULL,
    code character varying(50) COLLATE pg_catalog."default" NOT NULL,
    mac character varying(50) COLLATE pg_catalog."default" NOT NULL,
    update_time timestamp without time zone,
    add_time timestamp without time zone,
    CONSTRAINT station_white_list_pkey PRIMARY KEY (station_id, code)
);

ALTER TABLE IF EXISTS public.accesspoint
    ADD CONSTRAINT fk_s4ij9i441u1ibm88n8wj4w5lt FOREIGN KEY (station_id)
    REFERENCES public.station (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_accesspoint_station_id
    ON public.accesspoint(station_id);


ALTER TABLE IF EXISTS public.config_content
    ADD CONSTRAINT fk_config_content_id_content_id FOREIGN KEY (id)
    REFERENCES public.content (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS config_content_pkey
    ON public.config_content(id);


ALTER TABLE IF EXISTS public.content
    ADD CONSTRAINT fk_47li4qpcetc8web2s96ugwhnc FOREIGN KEY (station_id)
    REFERENCES public.station (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.content
    ADD CONSTRAINT fk_6fl30jaj1ouw3wamk4ms04p0b FOREIGN KEY (enddevice_id)
    REFERENCES public.enddevice (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_content_enddevice_id
    ON public.content(enddevice_id);


ALTER TABLE IF EXISTS public.enddevice
    ADD CONSTRAINT fk_3qif2492oh45794xm9nj65qyf FOREIGN KEY (accesspoint_id)
    REFERENCES public.accesspoint (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_enddevice_accesspoint_id
    ON public.enddevice(accesspoint_id);


ALTER TABLE IF EXISTS public.enddevice
    ADD CONSTRAINT fk_enddevice_controller_id_enddevice_id FOREIGN KEY (controller_id)
    REFERENCES public.enddevice (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.enddevice
    ADD CONSTRAINT fk_qh6kb6x2fepon0sviumwr6nrl FOREIGN KEY (station_id)
    REFERENCES public.station (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_enddevice_station_id
    ON public.enddevice(station_id);


ALTER TABLE IF EXISTS public.generation_content_message
    ADD CONSTRAINT fk_h8vf0yrbyhvcjry14bnpjdgqg FOREIGN KEY (accesspoint_id)
    REFERENCES public.accesspoint (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.image_content
    ADD CONSTRAINT fk_p37aqpcq5hwkmnau5ua2kwtsl FOREIGN KEY (id)
    REFERENCES public.content (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS image_content_pkey
    ON public.image_content(id);


ALTER TABLE IF EXISTS public.multi_segment_content
    ADD CONSTRAINT fk_1dcpkyhuue3hxjpjh07iaunt0 FOREIGN KEY (id)
    REFERENCES public.content (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS multi_segment_content_pkey
    ON public.multi_segment_content(id);


ALTER TABLE IF EXISTS public.nfc_content
    ADD CONSTRAINT fk_hsg8o13rdiu4oqy0tnt96atte FOREIGN KEY (id)
    REFERENCES public.content (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS nfc_content_pkey
    ON public.nfc_content(id);


ALTER TABLE IF EXISTS public.schedule_content
    ADD CONSTRAINT fk_us1qgsab9n6eodsok1db3j3ad FOREIGN KEY (id)
    REFERENCES public.content (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS schedule_content_pkey
    ON public.schedule_content(id);


ALTER TABLE IF EXISTS public.segment_content
    ADD CONSTRAINT fk_ns9qgsab9k6kbatok1db6j6ad FOREIGN KEY (id)
    REFERENCES public.content (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS segment_content_pkey
    ON public.segment_content(id);


ALTER TABLE IF EXISTS public.sgateway
    ADD CONSTRAINT fk_3ydbq4t19asp4e1x4sls7jna2 FOREIGN KEY (id)
    REFERENCES public.accesspoint (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS sgateway_pkey
    ON public.sgateway(id);


ALTER TABLE IF EXISTS public.sgateway_activation
    ADD CONSTRAINT fk_pp004wjord3dg2wcu7v3jknir FOREIGN KEY (sgateway_id)
    REFERENCES public.sgateway (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.slabel
    ADD CONSTRAINT fk_1n1gc1e331asajy0a55548d0q FOREIGN KEY (id)
    REFERENCES public.enddevice (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS slabel_pkey
    ON public.slabel(id);


ALTER TABLE IF EXISTS public.slabel_button
    ADD CONSTRAINT fk_5kf58cn0352l83s7oceg71pmw FOREIGN KEY (slabel_id)
    REFERENCES public.slabel (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.station_white_list
    ADD CONSTRAINT fk_jc1m4u8g87ijm12xr3nqys0yq FOREIGN KEY (station_id)
    REFERENCES public.station (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;