-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


ALTER TABLE IF EXISTS public.firmwarelabel DROP CONSTRAINT IF EXISTS firmwaredata_id;

ALTER TABLE IF EXISTS public.store_label_class DROP CONSTRAINT IF EXISTS store_label_state_id;



DROP TABLE IF EXISTS public.databasechangelog;

CREATE TABLE IF NOT EXISTS public.databasechangelog
(
    id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    author character varying(255) COLLATE pg_catalog."default" NOT NULL,
    filename character varying(255) COLLATE pg_catalog."default" NOT NULL,
    dateexecuted timestamp without time zone NOT NULL,
    orderexecuted integer NOT NULL,
    exectype character varying(10) COLLATE pg_catalog."default" NOT NULL,
    md5sum character varying(35) COLLATE pg_catalog."default",
    description character varying(255) COLLATE pg_catalog."default",
    comments character varying(255) COLLATE pg_catalog."default",
    tag character varying(255) COLLATE pg_catalog."default",
    liquibase character varying(20) COLLATE pg_catalog."default",
    contexts character varying(255) COLLATE pg_catalog."default",
    labels character varying(255) COLLATE pg_catalog."default",
    deployment_id character varying(10) COLLATE pg_catalog."default"
);

DROP TABLE IF EXISTS public.databasechangeloglock;

CREATE TABLE IF NOT EXISTS public.databasechangeloglock
(
    id integer NOT NULL,
    locked boolean NOT NULL,
    lockgranted timestamp without time zone,
    lockedby character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT databasechangeloglock_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.firmware_label_state;

CREATE TABLE IF NOT EXISTS public.firmware_label_state
(
    id bigint NOT NULL,
    station_code character varying(255) COLLATE pg_catalog."default",
    gwmac character varying(20) COLLATE pg_catalog."default",
    code character varying(20) COLLATE pg_catalog."default",
    system character varying(20) COLLATE pg_catalog."default",
    type character varying(20) COLLATE pg_catalog."default",
    inch character varying(20) COLLATE pg_catalog."default",
    type_code character varying(20) COLLATE pg_catalog."default",
    firmware_version integer,
    update_count integer,
    total_count integer,
    last_updated_time timestamp(6) without time zone,
    tag_class character varying(20) COLLATE pg_catalog."default"
);

DROP TABLE IF EXISTS public.firmwaredata;

CREATE TABLE IF NOT EXISTS public.firmwaredata
(
    id bigint NOT NULL,
    compsize integer NOT NULL,
    decompsize integer NOT NULL,
    customer character varying(255) COLLATE pg_catalog."default",
    filename character varying(255) COLLATE pg_catalog."default" NOT NULL,
    fwversion integer,
    jobnumber character varying(10) COLLATE pg_catalog."default",
    otamode character varying(10) COLLATE pg_catalog."default",
    sitecode character varying(10) COLLATE pg_catalog."default",
    system character varying(10) COLLATE pg_catalog."default",
    type character varying(20) COLLATE pg_catalog."default",
    tag_class character varying(50) COLLATE pg_catalog."default",
    inch character varying(10) COLLATE pg_catalog."default",
    type_code character varying(10) COLLATE pg_catalog."default",
    createdtime timestamp(6) without time zone,
    updatedtime timestamp(6) without time zone,
    binarydata character varying COLLATE pg_catalog."default",
    CONSTRAINT "PK_firmwaredata" PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.firmwarelabel;

CREATE TABLE IF NOT EXISTS public.firmwarelabel
(
    id bigint NOT NULL,
    fwversion integer,
    labeltype character varying(255) COLLATE pg_catalog."default",
    firmwaredata_id bigint NOT NULL,
    tag_class character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT "PK_firmwarelabel" PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.gwfirmwaredata;

CREATE TABLE IF NOT EXISTS public.gwfirmwaredata
(
    id bigint NOT NULL,
    filename character varying(255) COLLATE pg_catalog."default" NOT NULL,
    system character varying(20) COLLATE pg_catalog."default",
    type character varying(20) COLLATE pg_catalog."default",
    mode character varying(20) COLLATE pg_catalog."default",
    version character varying(20) COLLATE pg_catalog."default",
    md5sum character varying(50) COLLATE pg_catalog."default",
    binarydata text COLLATE pg_catalog."default",
    createdtime timestamp(6) without time zone,
    updatedtime timestamp(6) without time zone,
    CONSTRAINT "PK_gwfirmwaredata" PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.otaschedule;

CREATE TABLE IF NOT EXISTS public.otaschedule
(
    gwmac character varying(255) COLLATE pg_catalog."default" NOT NULL,
    code character varying(255) COLLATE pg_catalog."default",
    createdtime timestamp(6) without time zone,
    firmwareid character varying(255) COLLATE pg_catalog."default" NOT NULL,
    gwip character varying(255) COLLATE pg_catalog."default",
    otaset bigint,
    otatime timestamp(6) without time zone,
    stationcode character varying(255) COLLATE pg_catalog."default",
    updatedtime timestamp(6) without time zone,
    sent_to_gateway character varying(50) COLLATE pg_catalog."default" DEFAULT 'false'::character varying,
    CONSTRAINT "PK_otaschedule" PRIMARY KEY (firmwareid, gwmac)
);

DROP TABLE IF EXISTS public.shedlock;

CREATE TABLE IF NOT EXISTS public.shedlock
(
    name character varying(64) COLLATE pg_catalog."default" NOT NULL,
    locked_by character varying(255) COLLATE pg_catalog."default" NOT NULL,
    locked_at timestamp without time zone NOT NULL DEFAULT now(),
    lock_until timestamp without time zone NOT NULL,
    CONSTRAINT uk_shedlock_name UNIQUE (name)
);

DROP TABLE IF EXISTS public.store_label_class;

CREATE TABLE IF NOT EXISTS public.store_label_class
(
    id bigint NOT NULL,
    tag_class character varying(50) COLLATE pg_catalog."default",
    firmware_version integer,
    update_count integer,
    total_count integer,
    stationcode character varying(255) COLLATE pg_catalog."default",
    last_updated_time timestamp(6) without time zone,
    store_label_state_id bigint NOT NULL,
    CONSTRAINT "PK_store_label_class" PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.store_label_state;

CREATE TABLE IF NOT EXISTS public.store_label_state
(
    id bigint NOT NULL,
    station_code character varying(100) COLLATE pg_catalog."default",
    system character varying(20) COLLATE pg_catalog."default",
    type character varying(20) COLLATE pg_catalog."default",
    inch character varying(20) COLLATE pg_catalog."default",
    type_code character varying(20) COLLATE pg_catalog."default",
    update_count integer,
    total_count integer,
    last_updated_time timestamp(6) without time zone,
    CONSTRAINT "PK_store_label_state" PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.firmwarelabel
    ADD CONSTRAINT firmwaredata_id FOREIGN KEY (firmwaredata_id)
    REFERENCES public.firmwaredata (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.store_label_class
    ADD CONSTRAINT store_label_state_id FOREIGN KEY (store_label_state_id)
    REFERENCES public.store_label_state (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;