-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


ALTER TABLE IF EXISTS public.article_aud DROP CONSTRAINT IF EXISTS fk_rev_on_article_aud;

ALTER TABLE IF EXISTS public.end_device_articles DROP CONSTRAINT IF EXISTS fk_9jxn8oaj6k38s51b2kub4jkuc;

ALTER TABLE IF EXISTS public.end_device_articles DROP CONSTRAINT IF EXISTS fk_b8o71udimytqqkskh6gepnjsl;

ALTER TABLE IF EXISTS public.end_device_templates DROP CONSTRAINT IF EXISTS fk_7ywt1kcksihl1jiuya8h5ns5c;

ALTER TABLE IF EXISTS public.end_device_templates DROP CONSTRAINT IF EXISTS fk_sukjb7sjbn6bglc6u07txux8o;

ALTER TABLE IF EXISTS public.translation_language_content DROP CONSTRAINT IF EXISTS fk_language_id_translation_language;



DROP TABLE IF EXISTS public.access_level;

CREATE TABLE IF NOT EXISTS public.access_level
(
    id bigint NOT NULL,
    access_level character varying(255) COLLATE pg_catalog."default",
    title character varying(255) COLLATE pg_catalog."default",
    access_menu character varying(4000) COLLATE pg_catalog."default",
    access_action character varying(4000) COLLATE pg_catalog."default",
    CONSTRAINT "PK_accessLevel" PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.add_info_config;

CREATE TABLE IF NOT EXISTS public.add_info_config
(
    id bigint NOT NULL,
    name character varying(255) COLLATE pg_catalog."default",
    enable boolean NOT NULL
);

DROP TABLE IF EXISTS public.aims_portal_batch;

CREATE TABLE IF NOT EXISTS public.aims_portal_batch
(
    id bigint NOT NULL,
    created timestamp(6) without time zone,
    custom_batch_id character varying(255) COLLATE pg_catalog."default",
    last_modified timestamp(6) without time zone,
    message_provider character varying(255) COLLATE pg_catalog."default",
    status character varying(255) COLLATE pg_catalog."default",
    type character varying(255) COLLATE pg_catalog."default",
    station_code character varying(255) COLLATE pg_catalog."default",
    message_param character varying COLLATE pg_catalog."default",
    request_sequence bigint NOT NULL DEFAULT 0,
    number_of_items integer DEFAULT 0,
    server_id bigint DEFAULT 0,
    CONSTRAINT aims_portal_batch_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.aims_portal_property;

CREATE TABLE IF NOT EXISTS public.aims_portal_property
(
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    properties character varying(1048576) COLLATE pg_catalog."default",
    CONSTRAINT "PK_aimsPortalProperty" PRIMARY KEY (name)
);

DROP TABLE IF EXISTS public.aims_station_code;

CREATE TABLE IF NOT EXISTS public.aims_station_code
(
    id bigint NOT NULL,
    aims_station_code character varying(4000) COLLATE pg_catalog."default",
    city_name character varying(4000) COLLATE pg_catalog."default",
    coordinates character varying(4000) COLLATE pg_catalog."default",
    country_code character varying(4000) COLLATE pg_catalog."default",
    country_name character varying(4000) COLLATE pg_catalog."default",
    location character varying(4000) COLLATE pg_catalog."default",
    subdivision_code character varying(4000) COLLATE pg_catalog."default",
    subdivision_name character varying(4000) COLLATE pg_catalog."default",
    CONSTRAINT aims_station_code_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.app_settings;

CREATE TABLE IF NOT EXISTS public.app_settings
(
    id bigint NOT NULL,
    area_id bigint,
    station_code character varying(255) COLLATE pg_catalog."default",
    category character varying(255) COLLATE pg_catalog."default" NOT NULL,
    data character varying(4000) COLLATE pg_catalog."default",
    created timestamp(6) without time zone NOT NULL,
    last_modified timestamp(6) without time zone NOT NULL,
    CONSTRAINT "PK_app_settings" PRIMARY KEY (id),
    CONSTRAINT idx_app_settings_area_id UNIQUE (area_id, station_code, category)
);

DROP TABLE IF EXISTS public.area;

CREATE TABLE IF NOT EXISTS public.area
(
    id bigint NOT NULL,
    company character varying(255) COLLATE pg_catalog."default" NOT NULL,
    country character varying(255) COLLATE pg_catalog."default",
    region character varying(255) COLLATE pg_catalog."default",
    city character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT "PK_area" PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.article;

CREATE TABLE IF NOT EXISTS public.article
(
    article_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created timestamp(6) without time zone,
    last_modified timestamp(6) without time zone,
    name character varying(512) COLLATE pg_catalog."default",
    nfc_url character varying(255) COLLATE pg_catalog."default",
    data character varying COLLATE pg_catalog."default",
    station_code character varying(255) COLLATE pg_catalog."default" NOT NULL DEFAULT 'DEFAULT_STATION_CODE'::character varying,
    reserved_one character varying(255) COLLATE pg_catalog."default",
    reserved_two character varying(255) COLLATE pg_catalog."default",
    reserved_three character varying(255) COLLATE pg_catalog."default",
    custom_batch_id character varying(255) COLLATE pg_catalog."default",
    reserved json,
    CONSTRAINT article_pkey PRIMARY KEY (article_id, station_code)
);

DROP TABLE IF EXISTS public.article_aud;

CREATE TABLE IF NOT EXISTS public.article_aud
(
    article_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    station_code character varying(255) COLLATE pg_catalog."default" NOT NULL,
    rev integer NOT NULL,
    revtype smallint,
    created timestamp(6) without time zone,
    data character varying COLLATE pg_catalog."default",
    last_modified timestamp(6) without time zone,
    name character varying(512) COLLATE pg_catalog."default",
    nfc_url character varying(255) COLLATE pg_catalog."default",
    custom_batch_id character varying(255) COLLATE pg_catalog."default",
    reserved_one character varying(255) COLLATE pg_catalog."default",
    reserved_two character varying(255) COLLATE pg_catalog."default",
    reserved_three character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT article_aud_pkey PRIMARY KEY (article_id, station_code, rev)
);

DROP TABLE IF EXISTS public.article_mapping;

CREATE TABLE IF NOT EXISTS public.article_mapping
(
    station_code character varying(255) COLLATE pg_catalog."default" NOT NULL,
    article_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    ean character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT article_mapping_pkey PRIMARY KEY (station_code, ean)
);

DROP TABLE IF EXISTS public.article_master;

CREATE TABLE IF NOT EXISTS public.article_master
(
    article_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    master_data character varying COLLATE pg_catalog."default",
    created timestamp(6) without time zone,
    last_modified timestamp(6) without time zone,
    CONSTRAINT pk_article_master PRIMARY KEY (article_id)
);

DROP TABLE IF EXISTS public.article_schedule;

CREATE TABLE IF NOT EXISTS public.article_schedule
(
    id bigint NOT NULL,
    station_code character varying(255) COLLATE pg_catalog."default" NOT NULL,
    file_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    binary_data text COLLATE pg_catalog."default",
    time_zone character varying(50) COLLATE pg_catalog."default" NOT NULL,
    schedule_time character varying(50) COLLATE pg_catalog."default" NOT NULL,
    created timestamp(6) without time zone,
    last_modified_date timestamp(6) without time zone,
    file_status character varying(50) COLLATE pg_catalog."default" NOT NULL,
    process_date timestamp(6) without time zone,
    execution_result text COLLATE pg_catalog."default",
    CONSTRAINT article_schedule_pk PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.bletag_setting;

CREATE TABLE IF NOT EXISTS public.bletag_setting
(
    id bigint NOT NULL,
    createtime character varying(4000) COLLATE pg_catalog."default",
    labelid character varying(4000) COLLATE pg_catalog."default",
    macid character varying(255) COLLATE pg_catalog."default" NOT NULL,
    updatetime character varying(4000) COLLATE pg_catalog."default",
    url character varying(4000) COLLATE pg_catalog."default",
    CONSTRAINT bletag_setting_pkey PRIMARY KEY (id),
    CONSTRAINT uk_f7oluugj4mxfjhj7t4b5ptxr0 UNIQUE (macid)
);

DROP TABLE IF EXISTS public.button_config;

CREATE TABLE IF NOT EXISTS public.button_config
(
    id bigint NOT NULL,
    config_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    button_set character varying(400) COLLATE pg_catalog."default" NOT NULL,
    realtime_config_hibernate boolean NOT NULL,
    created timestamp(6) without time zone NOT NULL,
    last_modified timestamp(6) without time zone NOT NULL,
    CONSTRAINT button_config_pk PRIMARY KEY (id),
    CONSTRAINT uk_button_config_name UNIQUE (config_name),
    CONSTRAINT uk_button_set_hibernate UNIQUE (button_set, realtime_config_hibernate)
);

DROP TABLE IF EXISTS public.central_summary;

CREATE TABLE IF NOT EXISTS public.central_summary
(
    store_id bigint NOT NULL,
    total_store_count bigint,
    issued_store_count bigint,
    last_update_inprogress_count bigint,
    last_updatetotal_count bigint,
    updated_label_count bigint,
    in_progress_label_count bigint,
    not_updated_label_count bigint,
    total_updated_label_count bigint,
    low_battery_count bigint,
    online_label_count bigint,
    offline_label_count bigint,
    bad_signal_label_count bigint,
    online_gw_count bigint,
    not_ready_gw_count bigint,
    offline_gw_count bigint,
    total_label_count bigint,
    total_assigned_product_count bigint,
    total_product_count bigint,
    mis_used_label_count bigint,
    last_modified character varying(50) COLLATE pg_catalog."default",
    very_good_battery_count bigint,
    good_battery_count bigint,
    replace_battery_count bigint,
    CONSTRAINT "PK_central_summary" PRIMARY KEY (store_id)
);

DROP TABLE IF EXISTS public.customer_info;

CREATE TABLE IF NOT EXISTS public.customer_info
(
    id bigint NOT NULL,
    station_code character varying(255) COLLATE pg_catalog."default",
    language character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description character varying(255) COLLATE pg_catalog."default",
    usage character varying(50) COLLATE pg_catalog."default" DEFAULT 'DEFAULT'::character varying,
    priority integer,
    area_id bigint,
    CONSTRAINT "PK_customerInfo" PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.customer_info_contents;

CREATE TABLE IF NOT EXISTS public.customer_info_contents
(
    id bigint NOT NULL,
    type character varying(255) COLLATE pg_catalog."default" NOT NULL,
    split character varying(255) COLLATE pg_catalog."default" NOT NULL,
    file_name character varying(255) COLLATE pg_catalog."default",
    content text COLLATE pg_catalog."default",
    CONSTRAINT "PK_customer_info_contents" PRIMARY KEY (id, type, split)
);

DROP TABLE IF EXISTS public.dashboard_log;

CREATE TABLE IF NOT EXISTS public.dashboard_log
(
    log_id bigint NOT NULL,
    type bigint,
    user_name character varying(255) COLLATE pg_catalog."default",
    url character varying(255) COLLATE pg_catalog."default",
    json_data character varying COLLATE pg_catalog."default",
    result character varying(255) COLLATE pg_catalog."default",
    "time" timestamp(6) without time zone
);

DROP TABLE IF EXISTS public.dashboard_role;

CREATE TABLE IF NOT EXISTS public.dashboard_role
(
    role_id bigint NOT NULL,
    role_name character varying(80) COLLATE pg_catalog."default",
    CONSTRAINT "PK_dashboard_role" PRIMARY KEY (role_id)
);

DROP TABLE IF EXISTS public.dashboard_settings;

CREATE TABLE IF NOT EXISTS public.dashboard_settings
(
    id bigint NOT NULL,
    category character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created timestamp(6) without time zone,
    item character varying(255) COLLATE pg_catalog."default",
    last_modified timestamp(6) without time zone,
    param_1 character varying(4000) COLLATE pg_catalog."default",
    param_10 character varying(255) COLLATE pg_catalog."default",
    param_2 character varying(255) COLLATE pg_catalog."default",
    param_3 character varying(255) COLLATE pg_catalog."default",
    param_4 character varying(255) COLLATE pg_catalog."default",
    param_5 character varying(255) COLLATE pg_catalog."default",
    param_6 character varying(255) COLLATE pg_catalog."default",
    param_7 character varying(255) COLLATE pg_catalog."default",
    param_8 character varying(255) COLLATE pg_catalog."default",
    param_9 character varying(255) COLLATE pg_catalog."default",
    param_descr character varying(1000) COLLATE pg_catalog."default",
    value character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT dashboard_settings_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.dashboard_user;

CREATE TABLE IF NOT EXISTS public.dashboard_user
(
    user_id bigint NOT NULL,
    user_name character varying(255) COLLATE pg_catalog."default",
    first_name character varying(255) COLLATE pg_catalog."default",
    last_name character varying(255) COLLATE pg_catalog."default",
    password character varying(255) COLLATE pg_catalog."default",
    email_address character varying(255) COLLATE pg_catalog."default",
    profile_path character varying(10000) COLLATE pg_catalog."default",
    user_group_id bigint,
    store_list character varying(2048) COLLATE pg_catalog."default",
    description character varying(255) COLLATE pg_catalog."default",
    last_modified_date timestamp(6) without time zone DEFAULT now(),
    access_level character varying(255) COLLATE pg_catalog."default",
    permission_key character varying(255) COLLATE pg_catalog."default",
    permission_value character varying(4000) COLLATE pg_catalog."default",
    email_alarm boolean DEFAULT false,
    email_report boolean DEFAULT false,
    phone_number character varying(255) COLLATE pg_catalog."default",
    temporary boolean DEFAULT false,
    CONSTRAINT "PK_dashboard_user" PRIMARY KEY (user_id),
    CONSTRAINT dashboard_user_user_name_key UNIQUE (user_name)
);

DROP TABLE IF EXISTS public.dashboard_user_group;

CREATE TABLE IF NOT EXISTS public.dashboard_user_group
(
    user_group_id bigint NOT NULL,
    user_group_name character varying(255) COLLATE pg_catalog."default",
    role_list character varying(2048) COLLATE pg_catalog."default",
    description character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT "PK_dashboard_user_group" PRIMARY KEY (user_group_id)
);

DROP TABLE IF EXISTS public.dashboard_user_session;

CREATE TABLE IF NOT EXISTS public.dashboard_user_session
(
    user_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    session_id character varying(255) COLLATE pg_catalog."default",
    last_access_time timestamp(6) without time zone,
    last_failure_time timestamp(6) without time zone,
    failure_count bigint,
    CONSTRAINT "PK_dashboard_user_session" PRIMARY KEY (user_name)
);

DROP TABLE IF EXISTS public.databasechangelog;

CREATE TABLE IF NOT EXISTS public.databasechangelog
(
    id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    author character varying(255) COLLATE pg_catalog."default" NOT NULL,
    filename character varying(255) COLLATE pg_catalog."default" NOT NULL,
    dateexecuted timestamp without time zone NOT NULL,
    orderexecuted integer NOT NULL,
    exectype character varying(10) COLLATE pg_catalog."default" NOT NULL,
    md5sum character varying(35) COLLATE pg_catalog."default",
    description character varying(255) COLLATE pg_catalog."default",
    comments character varying(255) COLLATE pg_catalog."default",
    tag character varying(255) COLLATE pg_catalog."default",
    liquibase character varying(20) COLLATE pg_catalog."default",
    contexts character varying(255) COLLATE pg_catalog."default",
    labels character varying(255) COLLATE pg_catalog."default",
    deployment_id character varying(10) COLLATE pg_catalog."default"
);

DROP TABLE IF EXISTS public.end_device;

CREATE TABLE IF NOT EXISTS public.end_device
(
    label_code character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created timestamp(6) without time zone,
    last_modified timestamp(6) without time zone,
    station_code character varying(255) COLLATE pg_catalog."default" NOT NULL DEFAULT 'DEFAULT_STATION_CODE'::character varying,
    template_manual boolean DEFAULT false,
    button_config_id bigint DEFAULT 1,
    CONSTRAINT end_device_pkey PRIMARY KEY (label_code)
);

DROP TABLE IF EXISTS public.end_device_add_info;

CREATE TABLE IF NOT EXISTS public.end_device_add_info
(
    label_code character varying(255) COLLATE pg_catalog."default" NOT NULL,
    station_code character varying(255) COLLATE pg_catalog."default" NOT NULL,
    add_info_1 character varying(255) COLLATE pg_catalog."default",
    add_info_2 character varying(255) COLLATE pg_catalog."default",
    add_info_3 character varying(255) COLLATE pg_catalog."default",
    add_info_4 character varying(255) COLLATE pg_catalog."default",
    add_info_5 character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT end_device_add_info_pkey PRIMARY KEY (label_code)
);

DROP TABLE IF EXISTS public.end_device_articles;

CREATE TABLE IF NOT EXISTS public.end_device_articles
(
    label_code character varying(255) COLLATE pg_catalog."default" NOT NULL,
    article_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    seq integer NOT NULL,
    station_code character varying(255) COLLATE pg_catalog."default" NOT NULL DEFAULT 'DEFAULT_STATION_CODE'::character varying,
    CONSTRAINT end_device_articles_pkey PRIMARY KEY (label_code, seq)
);

DROP TABLE IF EXISTS public.end_device_template_type;

CREATE TABLE IF NOT EXISTS public.end_device_template_type
(
    label_code character varying(255) COLLATE pg_catalog."default" NOT NULL,
    type character varying(255) COLLATE pg_catalog."default" NOT NULL,
    page integer NOT NULL,
    station_code character varying(255) COLLATE pg_catalog."default" NOT NULL DEFAULT 'DEFAULT_STATION_CODE'::character varying,
    CONSTRAINT end_device_template_type_pkey PRIMARY KEY (label_code, page)
);

DROP TABLE IF EXISTS public.end_device_templates;

CREATE TABLE IF NOT EXISTS public.end_device_templates
(
    label_code character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    page integer NOT NULL,
    station_code character varying(255) COLLATE pg_catalog."default" NOT NULL DEFAULT 'DEFAULT_STATION_CODE'::character varying,
    CONSTRAINT end_device_templates_pkey PRIMARY KEY (label_code, page)
);

DROP TABLE IF EXISTS public.favorite_button;

CREATE TABLE IF NOT EXISTS public.favorite_button
(
    id bigint NOT NULL,
    station_code character varying(255) COLLATE pg_catalog."default",
    type character varying(255) COLLATE pg_catalog."default" NOT NULL,
    menu integer,
    description character varying(255) COLLATE pg_catalog."default",
    priority integer,
    area_id bigint,
    CONSTRAINT "PK_favoriteBtn_id" PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.file_result;

CREATE TABLE IF NOT EXISTS public.file_result
(
    id bigint NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created timestamp(6) without time zone,
    result character varying(255) COLLATE pg_catalog."default",
    total integer NOT NULL,
    success integer NOT NULL,
    fail integer NOT NULL,
    completed timestamp(6) without time zone,
    binary_data text COLLATE pg_catalog."default",
    station_code character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT file_result_id PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.images_on_template;

CREATE TABLE IF NOT EXISTS public.images_on_template
(
    id bigint NOT NULL,
    area_id bigint,
    station_code character varying(255) COLLATE pg_catalog."default",
    file_name character varying(255) COLLATE pg_catalog."default",
    content text COLLATE pg_catalog."default",
    created timestamp(6) without time zone NOT NULL,
    last_modified timestamp(6) without time zone NOT NULL,
    CONSTRAINT "PK_images_on_template" PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.lcd_article;

CREATE TABLE IF NOT EXISTS public.lcd_article
(
    article_id character varying(512) COLLATE pg_catalog."default" NOT NULL,
    company character varying(512) COLLATE pg_catalog."default",
    station_code character varying(512) COLLATE pg_catalog."default" NOT NULL,
    created timestamp(6) without time zone,
    CONSTRAINT m_lcd_article_pk PRIMARY KEY (article_id, station_code)
);

DROP TABLE IF EXISTS public.lcd_quick_play_mapping;

CREATE TABLE IF NOT EXISTS public.lcd_quick_play_mapping
(
    article_id character varying(512) COLLATE pg_catalog."default" NOT NULL,
    customer character varying(512) COLLATE pg_catalog."default",
    station_code character varying(512) COLLATE pg_catalog."default" NOT NULL,
    duration integer,
    composition_id character varying(512) COLLATE pg_catalog."default" NOT NULL,
    screen_id character varying(512) COLLATE pg_catalog."default" NOT NULL,
    created timestamp(6) without time zone,
    last_modified timestamp(6) without time zone,
    CONSTRAINT quick_play_mapping_pk PRIMARY KEY (article_id, station_code, composition_id, screen_id)
);

DROP TABLE IF EXISTS public.led_pattern;

CREATE TABLE IF NOT EXISTS public.led_pattern
(
    id bigint NOT NULL,
    name character varying(255) COLLATE pg_catalog."default",
    active_time integer,
    in_active_time integer,
    idle_time integer,
    active_count integer,
    CONSTRAINT "PK_ledPattern" PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.mail;

CREATE TABLE IF NOT EXISTS public.mail
(
    id bigint NOT NULL,
    mail_address character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_Mail" PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.payment_license;

CREATE TABLE IF NOT EXISTS public.payment_license
(
    id bigint NOT NULL,
    active boolean,
    license_id character varying(255) COLLATE pg_catalog."default",
    payment_license_type character varying(255) COLLATE pg_catalog."default",
    server_type character varying(255) COLLATE pg_catalog."default",
    expiry_date timestamp(6) without time zone,
    version character varying(255) COLLATE pg_catalog."default",
    number_of_store integer,
    installation_date timestamp(6) without time zone,
    encoded_license character varying COLLATE pg_catalog."default",
    last_modified_date timestamp(6) without time zone,
    use_layout_designer boolean DEFAULT true,
    CONSTRAINT payment_license_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.report_config;

CREATE TABLE IF NOT EXISTS public.report_config
(
    id bigint NOT NULL,
    mail_host character varying(255) COLLATE pg_catalog."default",
    mail_port character varying(255) COLLATE pg_catalog."default",
    mail_username character varying(255) COLLATE pg_catalog."default",
    mail_pw character varying(255) COLLATE pg_catalog."default",
    mail_title character varying(255) COLLATE pg_catalog."default",
    mail_message character varying(255) COLLATE pg_catalog."default",
    mail_encoding character varying(255) COLLATE pg_catalog."default",
    mail_auth character varying(255) COLLATE pg_catalog."default",
    report_file_path character varying(255) COLLATE pg_catalog."default",
    report_hour integer,
    report_use boolean,
    report_minute integer,
    CONSTRAINT "PK_reportConfig" PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.revinfo;

CREATE TABLE IF NOT EXISTS public.revinfo
(
    rev integer NOT NULL,
    revtstmp bigint,
    CONSTRAINT revinfo_pkey PRIMARY KEY (rev)
);

DROP TABLE IF EXISTS public.server;

CREATE TABLE IF NOT EXISTS public.server
(
    id bigint NOT NULL,
    code character varying(100) COLLATE pg_catalog."default",
    group_id character varying(100) COLLATE pg_catalog."default",
    portal_revision character varying(50) COLLATE pg_catalog."default",
    portal_version character varying(50) COLLATE pg_catalog."default",
    description character varying(255) COLLATE pg_catalog."default",
    ip_address character varying(255) COLLATE pg_catalog."default",
    type character varying(50) COLLATE pg_catalog."default",
    lb_ip_address character varying(255) COLLATE pg_catalog."default",
    lb_port integer,
    version bigint,
    port integer,
    last_connection_date timestamp without time zone,
    CONSTRAINT server_pkey PRIMARY KEY (id),
    CONSTRAINT uk_server_code UNIQUE (code)
);

DROP TABLE IF EXISTS public.server_node;

CREATE TABLE IF NOT EXISTS public.server_node
(
    id bigint NOT NULL,
    ip_address character varying(255) COLLATE pg_catalog."default" NOT NULL,
    code character varying(100) COLLATE pg_catalog."default" NOT NULL,
    port integer NOT NULL,
    node_type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    node_status character varying(20) COLLATE pg_catalog."default" NOT NULL,
    last_connection_date timestamp without time zone,
    version character varying(50) COLLATE pg_catalog."default",
    revision character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT server_node_pkey PRIMARY KEY (id),
    CONSTRAINT uk_server_node UNIQUE (ip_address, port, node_type)
);

DROP TABLE IF EXISTS public.shedlock;

CREATE TABLE IF NOT EXISTS public.shedlock
(
    name character varying(64) COLLATE pg_catalog."default" NOT NULL,
    locked_by character varying(255) COLLATE pg_catalog."default" NOT NULL,
    locked_at timestamp without time zone NOT NULL DEFAULT now(),
    lock_until timestamp without time zone NOT NULL,
    CONSTRAINT uk_shedlock_name UNIQUE (name)
);

DROP TABLE IF EXISTS public.standard_data_map;

CREATE TABLE IF NOT EXISTS public.standard_data_map
(
    id bigint NOT NULL,
    mapped_article_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    mapped_station_code character varying(255) COLLATE pg_catalog."default" NOT NULL,
    mapped_article_name character varying(255) COLLATE pg_catalog."default",
    mapped_nfc character varying(255) COLLATE pg_catalog."default",
    mapped_origin_price character varying(255) COLLATE pg_catalog."default",
    mapped_sale_price character varying(255) COLLATE pg_catalog."default",
    mapped_discount_percentage character varying(255) COLLATE pg_catalog."default",
    mapped_reserved_one character varying(255) COLLATE pg_catalog."default",
    mapped_reserved_two character varying(255) COLLATE pg_catalog."default",
    mapped_reserved_three character varying(255) COLLATE pg_catalog."default",
    standard_data_map_list text COLLATE pg_catalog."default" NOT NULL,
    reserved json,
    segment_config_map_list text COLLATE pg_catalog."default"
);

DROP TABLE IF EXISTS public.system_image;

CREATE TABLE IF NOT EXISTS public.system_image
(
    location character varying(255) COLLATE pg_catalog."default" NOT NULL,
    file_name character varying(255) COLLATE pg_catalog."default",
    file_data text COLLATE pg_catalog."default",
    CONSTRAINT "PK_system_image" PRIMARY KEY (location)
);

DROP TABLE IF EXISTS public.tap_and_go_info;

CREATE TABLE IF NOT EXISTS public.tap_and_go_info
(
    user_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    station_code character varying(255) COLLATE pg_catalog."default" NOT NULL,
    article_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    product_name character varying(512) COLLATE pg_catalog."default",
    count integer,
    label_code character varying(20) COLLATE pg_catalog."default",
    status_update_time timestamp(6) without time zone,
    accesspoint_ip_address character varying(20) COLLATE pg_catalog."default",
    accesspoint_mac character varying(20) COLLATE pg_catalog."default",
    modified timestamp(6) without time zone,
    CONSTRAINT "PK_tapAndGo" PRIMARY KEY (user_id, station_code, article_id)
);

DROP TABLE IF EXISTS public.template;

CREATE TABLE IF NOT EXISTS public.template
(
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created timestamp(6) without time zone,
    height integer NOT NULL,
    last_modified timestamp(6) without time zone,
    type character varying(255) COLLATE pg_catalog."default",
    width integer NOT NULL,
    data character varying COLLATE pg_catalog."default",
    station_code character varying(255) COLLATE pg_catalog."default" NOT NULL DEFAULT 'DEFAULT_STATION_CODE'::character varying,
    custom_batch_id character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT template_pkey PRIMARY KEY (name, station_code)
);

DROP TABLE IF EXISTS public.template_area;

CREATE TABLE IF NOT EXISTS public.template_area
(
    type_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    template_size character varying(255) COLLATE pg_catalog."default" NOT NULL,
    area_key character varying(255) COLLATE pg_catalog."default" NOT NULL,
    area_value character varying(255) COLLATE pg_catalog."default" NOT NULL,
    template_name character varying(255) COLLATE pg_catalog."default",
    created timestamp(6) without time zone,
    last_modified timestamp(6) without time zone,
    template_color character varying(255) COLLATE pg_catalog."default" NOT NULL DEFAULT 'BWR'::character varying,
    CONSTRAINT template_area_pk PRIMARY KEY (type_name, template_size, template_color, area_key, area_value)
);

DROP TABLE IF EXISTS public.template_decision;

CREATE TABLE IF NOT EXISTS public.template_decision
(
    station_code character varying(64) COLLATE pg_catalog."default" NOT NULL,
    page integer NOT NULL,
    default_group character varying(255) COLLATE pg_catalog."default" NOT NULL,
    condition_list text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pk_template_decision UNIQUE (station_code, page)
);

DROP TABLE IF EXISTS public.template_group;

CREATE TABLE IF NOT EXISTS public.template_group
(
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description character varying(255) COLLATE pg_catalog."default",
    created timestamp(6) without time zone,
    last_modified timestamp(6) without time zone,
    CONSTRAINT template_group_pk PRIMARY KEY (name)
);

DROP TABLE IF EXISTS public.template_group_map;

CREATE TABLE IF NOT EXISTS public.template_group_map
(
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    station_code character varying(255) COLLATE pg_catalog."default" NOT NULL,
    group_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT template_group_map_pk PRIMARY KEY (name, station_code, group_name)
);

DROP TABLE IF EXISTS public.template_station;

CREATE TABLE IF NOT EXISTS public.template_station
(
    station_code character varying(255) COLLATE pg_catalog."default" NOT NULL,
    type_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    template_size character varying(255) COLLATE pg_catalog."default" NOT NULL,
    template_name character varying(255) COLLATE pg_catalog."default",
    created timestamp(6) without time zone,
    last_modified timestamp(6) without time zone,
    template_color character varying(255) COLLATE pg_catalog."default" NOT NULL DEFAULT 'BWR'::character varying,
    CONSTRAINT template_station_pk PRIMARY KEY (station_code, type_name, template_size, template_color)
);

DROP TABLE IF EXISTS public.template_type;

CREATE TABLE IF NOT EXISTS public.template_type
(
    type_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    template_size character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created timestamp(6) without time zone,
    last_modified timestamp(6) without time zone,
    template_color character varying(255) COLLATE pg_catalog."default" NOT NULL DEFAULT 'BWR'::character varying,
    CONSTRAINT template_type_pk PRIMARY KEY (type_name)
);

DROP TABLE IF EXISTS public.translation_language;

CREATE TABLE IF NOT EXISTS public.translation_language
(
    language_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    language_name character varying(255) COLLATE pg_catalog."default",
    default_language boolean,
    CONSTRAINT "PK_translation_language" PRIMARY KEY (language_id)
);

DROP TABLE IF EXISTS public.translation_language_content;

CREATE TABLE IF NOT EXISTS public.translation_language_content
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    file_name character varying(255) COLLATE pg_catalog."default",
    content text COLLATE pg_catalog."default",
    default_content text COLLATE pg_catalog."default",
    language_id bigint,
    CONSTRAINT "PK_translation_language_content" PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.warehouse_product;

CREATE TABLE IF NOT EXISTS public.warehouse_product
(
    id bigint NOT NULL,
    bin character varying(4000) COLLATE pg_catalog."default",
    created timestamp(6) without time zone,
    equip_no character varying(4000) COLLATE pg_catalog."default",
    gi_matr_id character varying(4000) COLLATE pg_catalog."default",
    last_modified timestamp(6) without time zone,
    line_nm character varying(4000) COLLATE pg_catalog."default",
    matr_code character varying(4000) COLLATE pg_catalog."default" NOT NULL,
    req_dt character varying(4000) COLLATE pg_catalog."default" NOT NULL,
    stored_qty character varying(4000) COLLATE pg_catalog."default",
    supply_qty character varying(4000) COLLATE pg_catalog."default",
    tag_id character varying(4000) COLLATE pg_catalog."default" NOT NULL,
    zone character varying(4000) COLLATE pg_catalog."default",
    CONSTRAINT warehouse_product_pkey PRIMARY KEY (id),
    CONSTRAINT uk_lxu8re3851a84vh6ukmitmwoy UNIQUE (tag_id)
);

DROP TABLE IF EXISTS public.white_list_pending_upload;

CREATE TABLE IF NOT EXISTS public.white_list_pending_upload
(
    station_code character varying(255) COLLATE pg_catalog."default" NOT NULL,
    label_code character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created timestamp(6) without time zone NOT NULL,
    article_id_list character varying(4000) COLLATE pg_catalog."default",
    template_name character varying(255) COLLATE pg_catalog."default",
    status character varying(50) COLLATE pg_catalog."default",
    arrow character varying(255) COLLATE pg_catalog."default",
    add_info_2 character varying(255) COLLATE pg_catalog."default",
    add_info_3 character varying(255) COLLATE pg_catalog."default",
    add_info_4 character varying(255) COLLATE pg_catalog."default",
    add_info_5 character varying(255) COLLATE pg_catalog."default",
    button_config_id bigint DEFAULT 1,
    CONSTRAINT uk_white_list_pending_upload UNIQUE (station_code, label_code)
);

ALTER TABLE IF EXISTS public.article_aud
    ADD CONSTRAINT fk_rev_on_article_aud FOREIGN KEY (rev)
    REFERENCES public.revinfo (rev) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.end_device_articles
    ADD CONSTRAINT fk_9jxn8oaj6k38s51b2kub4jkuc FOREIGN KEY (article_id, station_code)
    REFERENCES public.article (article_id, station_code) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "idx_enddevice_articles_station_and_articleId"
    ON public.end_device_articles(article_id, station_code);


ALTER TABLE IF EXISTS public.end_device_articles
    ADD CONSTRAINT fk_b8o71udimytqqkskh6gepnjsl FOREIGN KEY (label_code)
    REFERENCES public.end_device (label_code) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.end_device_templates
    ADD CONSTRAINT fk_7ywt1kcksihl1jiuya8h5ns5c FOREIGN KEY (name, station_code)
    REFERENCES public.template (name, station_code) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.end_device_templates
    ADD CONSTRAINT fk_sukjb7sjbn6bglc6u07txux8o FOREIGN KEY (label_code)
    REFERENCES public.end_device (label_code) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.translation_language_content
    ADD CONSTRAINT fk_language_id_translation_language FOREIGN KEY (language_id)
    REFERENCES public.translation_language (language_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;