"""Authoritative model gate: required schedule version, active-scope identity, retry due time.

Revision ID: 0008_authoritative_model_gate
Revises: 0007_audit_reconciliation
Create Date: 2026-09-03

Reserved for #21 by the AD-016 plan (Task 8). Additive; three changes:

1. ``workflow_schedule.configuration_version_id`` becomes NOT NULL. The gate
   refuses to run while any schedule lacks a version and names each such row.
   It never inserts a version of its own: a schedule whose configuration is
   unknown is recreated through ``esl-admin schedules create``, which records
   the version it was created under (#15), not patched by a migration.
2. A partial unique index makes the *active* schedule identity per workflow
   and store unique (architecture 5.9). Partial on ``enabled`` so a disabled
   schedule stays as history beside its replacement.
3. ``workflow_execution.retry_not_before`` gives a ``RETRY_WAIT`` execution a
   durable due time, so a retry delay survives a process restart instead of
   living only in the worker's pick interval (#102 recorded limit).
4. ``execution_step.sequence`` gives step attempts a monotonic start order, as
   0007 did for events: a coarse host clock stamps every step of one run with
   the same instant, and the step listing must not then fall to heap order.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0008_authoritative_model_gate"
down_revision: str | None = "0007_audit_reconciliation"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

ACTIVE_SCOPE_INDEX = "uq_workflow_schedule_active_scope"


def _refuse_schedules_without_a_version() -> None:
    """Abort, naming every schedule the gate would otherwise have to invent a version for."""

    rows = op.get_bind().execute(
        sa.text(
            "SELECT id, workflow_name, store_code FROM workflow_schedule "
            "WHERE configuration_version_id IS NULL ORDER BY created_at, id"
        )
    ).all()
    if not rows:
        return
    listed = "; ".join(f"{row.id} ({row.workflow_name}/{row.store_code})" for row in rows)
    raise RuntimeError(
        "0008_authoritative_model_gate refused: "
        f"{len(rows)} workflow_schedule row(s) have no configuration_version_id: {listed}. "
        "Recreate these schedules with `esl-admin schedules create` so each records the "
        "configuration version it runs under, then rerun the upgrade. "
        "The migration does not assign a version itself."
    )


def upgrade() -> None:
    """Apply the gate after preflight; nothing is written before preflight passes."""

    _refuse_schedules_without_a_version()

    op.alter_column(
        "workflow_schedule",
        "configuration_version_id",
        existing_type=postgresql.UUID(as_uuid=True),
        nullable=False,
    )
    op.create_index(
        ACTIVE_SCOPE_INDEX,
        "workflow_schedule",
        ["workflow_name", "store_code"],
        unique=True,
        postgresql_where=sa.text("enabled"),
    )
    op.add_column(
        "workflow_execution",
        sa.Column("retry_not_before", sa.DateTime(timezone=True), nullable=True),
    )
    # Existing rows are numbered by the best order they carry, start time then
    # attempt, before the identity takes over for new rows. Physical order is
    # not used: an updated row is a new tuple in PostgreSQL, so heap order on
    # execution_step already differs from insertion order.
    op.add_column("execution_step", sa.Column("sequence", sa.BigInteger(), nullable=True))
    op.execute(
        sa.text(
            "UPDATE execution_step AS s SET sequence = numbered.rn FROM ("
            " SELECT id, row_number() OVER (ORDER BY started_at, attempt, id) AS rn"
            " FROM execution_step) AS numbered WHERE s.id = numbered.id"
        )
    )
    op.alter_column("execution_step", "sequence", nullable=False)
    op.execute(
        sa.text(
            "ALTER TABLE execution_step ALTER COLUMN sequence "
            "ADD GENERATED BY DEFAULT AS IDENTITY"
        )
    )
    op.execute(
        sa.text(
            "SELECT setval(pg_get_serial_sequence('execution_step', 'sequence'), "
            "COALESCE((SELECT MAX(sequence) FROM execution_step), 0) + 1, false)"
        )
    )
    op.create_unique_constraint("uq_execution_step_sequence", "execution_step", ["sequence"])


def downgrade() -> None:
    """Remove exactly what 0008 added; no row is changed."""

    op.drop_constraint("uq_execution_step_sequence", "execution_step", type_="unique")
    op.drop_column("execution_step", "sequence")
    op.drop_column("workflow_execution", "retry_not_before")
    op.drop_index(ACTIVE_SCOPE_INDEX, table_name="workflow_schedule")
    op.alter_column(
        "workflow_schedule",
        "configuration_version_id",
        existing_type=postgresql.UUID(as_uuid=True),
        nullable=True,
    )
